# configuration used in various scripts

def getConfig():
    return __scriptsConfig()


class __scriptsConfig:
    CLASS_FEATURE_FILTER = {
        'ARTIFICER': {'shared': {'asi',
                                'prof_bonus',
                                'slots',
                                'spells_known'},
                    'unique': {'Alchemist', 'Gunsmith'}},
        'BARBARIAN': {'shared': {'asi',
                                'prof_bonus',
                                'rage',
                                'rage_damage'},
                    'unique': {'Path of the Ancestral Guardian',
                                'Path of the Battlerager',
                                'Path of the Berserker',
                                'Path of the Storm Herald',
                                'Path of the Totem Warrior',
                                'Path of the Zealot'}},
        'BARD': {'shared': {'asi',
                            'inspiration',
                            'prof_bonus',
                            'slots',
                            'song_of_rest',
                            'spells_known'},
                'unique': {'College of Glamour',
                            'College of Lore',
                            'College of Satire',
                            'College of Swords',
                            'College of Valor',
                            'College of Whispers'}},
        'CLERIC': {'shared': {'asi',
                            'channel_divinity',
                            'destroy_undead',
                            'prof_bonus',
                            'slots',
                            },
                'unique': {'Divine Domain: Arcana',
                            'Divine Domain: Death',
                            'Divine Domain: Forge',
                            'Divine Domain: Grave',
                            'Divine Domain: Knowledge',
                            'Divine Domain: Life',
                            'Divine Domain: Light',
                            'Divine Domain: Nature',
                            'Divine Domain: Tempest',
                            'Divine Domain: Trickery',
                            'Divine Domain: War'}},
        'DRUID': {'shared': {'asi',
                            'prof_bonus',
                            'slots',
                            'wild_shape_cr'},
                'unique': {'Druid Circle: Circle of Dreams',
                            'Druid Circle: Circle of Spores',
                            'Druid Circle: Circle of the Land',
                            'Druid Circle: Circle of the Moon',
                            'Druid Circle: Circle of the Shepherd'}
            },
        'FIGHTER': {'shared': {'action_surge',
                            'asi',
                            'attacks',
                            'indomitable',
                            'prof_bonus',
                            'second_wind',
                            'slots',
                            },
                    'unique': {'Martial Archetype: Arcane Archer',
                            'Martial Archetype: Battle Master',
                            'Martial Archetype: Cavalier',
                            'Martial Archetype: Champion',
                            'Martial Archetype: Eldritch Knight',
                            'Martial Archetype: Purple Dragon Knight',
                            'Martial Archetype: Samurai'}},
        'MONK': {'shared': {'asi',
                            'ki_points',
                            'martial_arts_die',
                            'prof_bonus',
                            'unarmed_movement'},
                'unique': {'Monastic Tradition: Way of Shadow',
                            'Monastic Tradition: Way of the Drunken Master',
                            'Monastic Tradition: Way of the Four Elements',
                            'Monastic Tradition: Way of the Kensei',
                            'Monastic Tradition: Way of the Long Death',
                            'Monastic Tradition: Way of the Open Hand',
                            'Monastic Tradition: Way of the Sun Soul'}},
        'PALADIN': {'shared': {'asi',
                            'attacks',
                            'lay_on_hands',
                            'prof_bonus',
                            'slots',
                    },
                    'unique': {'Oathbreaker',
                            'Sacred Oath: Oath of Conquest',
                            'Sacred Oath: Oath of Devotion',
                            'Sacred Oath: Oath of Redemption',
                            'Sacred Oath: Oath of Vengeance',
                            'Sacred Oath: Oath of the Ancients',
                            'Sacred Oath: Oath of the Crown'}},
        'RANGER': {'shared': {'asi',
                            'attacks',
                            'prof_bonus',
                            'slots',
                            'spells_known'},
                'unique': {'Ranger Archetype: Beast Master',
                            'Ranger Archetype: Gloom Stalker',
                            'Ranger Archetype: Horizon Walker',
                            'Ranger Archetype: Hunter',
                            'Ranger Archetype: Monster Slayer'}},
        'ROGUE': {'shared': {'asi',
                            'prof_bonus',
                            'slots',
                            'sneak_attack',
                            'spells_known'},
                'unique': {'Roguish Archetype: Arcane Trickster',
                            'Roguish Archetype: Assassin',
                            'Roguish Archetype: Inquisitive',
                            'Roguish Archetype: Mastermind',
                            'Roguish Archetype: Scout',
                            'Roguish Archetype: Swashbuckler',
                            'Roguish Archetype: Thief'}},
        'SORCERER': {'shared': {'asi',
                                
                                'metamagic_options',
                                'prof_bonus',
                                'slots',
                                'sorcery_points',
                                'spells_known'},
                    'unique': {'Sorcerous Origin: Divine Soul',
                                'Sorcerous Origin: Draconic Bloodline',
                                'Sorcerous Origin: Shadow Magic',
                                'Sorcerous Origin: Storm',
                                'Sorcerous Origin: Wild Magic'}},
        'WARLOCK': {'shared': {'asi',
                            'invocations_known',
                            'prof_bonus',
                            'slots',
                            'spells_known'},
                    'unique': {'Otherwordly Patron: The Celestial',
                            'Otherwordly Patron: The Hexblade',
                            'Otherworldly Patron: The Archfey',
                            'Otherworldly Patron: The Fiend',
                            'Otherworldly Patron: The Great Old One',
                            'Otherworldly Patron: The Undying'}},
        'WIZARD': {'shared': {'asi',
                            'prof_bonus',
                            'slots',
                },
                'unique': {'Arcane Tradition: Bladesinger',
                            'Arcane Tradition: School of Abjuration',
                            'Arcane Tradition: School of Conjuration',
                            'Arcane Tradition: School of Divination',
                            'Arcane Tradition: School of Enchantment',
                            'Arcane Tradition: School of Evocation',
                            'Arcane Tradition: School of Illusion',
                            'Arcane Tradition: School of Necromancy',
                            'Arcane Tradition: School of Transmutation',
                            'Arcane Tradition: War Magic'}
                            }
        }

    TRANSLATE_NAMES_TO_URL_NAMES = {
        'ARTIFICER': {
            'Alchemist': "alchemist", 
            'Gunsmith': "gunslinger"},

        'BARBARIAN': {
            'Path of the Ancestral Guardian': "ancestral_guardian",
            'Path of the Battlerager': "battlerager",
            'Path of the Berserker': "berserker",
            'Path of the Storm Herald': "storm_herald",
            'Path of the Totem Warrior': "totem_warrior",
            'Path of the Zealot': "zealot"
            },
        'BARD': {
            'College of Glamour': "glamour",
            'College of Lore': "lore",
            'College of Satire': "satire",
            'College of Swords': "swords",
            'College of Valor': "valor",
            'College of Whispers': "whispers"
            },
        'CLERIC': {
            'Divine Domain: Arcana': "arcana",
            'Divine Domain: Death': "death",
            'Divine Domain: Forge': "forge",
            'Divine Domain: Grave': "grave",
            'Divine Domain: Knowledge': "knowledge",
            'Divine Domain: Life': "life",
            'Divine Domain: Light': "light",
            'Divine Domain: Nature': "nature",
            'Divine Domain: Tempest': "tempest",
            'Divine Domain: Trickery': "trickery",
            'Divine Domain: War': "war"
            },
        'DRUID': {
            'Druid Circle: Circle of Dreams': "dreams",
            'Druid Circle: Circle of Spores': "spores",
            'Druid Circle: Circle of the Land': "land",
            'Druid Circle: Circle of the Moon': "moon",
            'Druid Circle: Circle of the Shepherd': "shepherd"
            },
        'FIGHTER': {
            'Martial Archetype: Arcane Archer': "arcane_archer",
            'Martial Archetype: Battle Master': "battle_master",
            'Martial Archetype: Cavalier': "cavalier",
            'Martial Archetype: Champion': "champion",
            'Martial Archetype: Eldritch Knight': "eldritch_knight",
            'Martial Archetype: Purple Dragon Knight': "purple_dragon",
            'Martial Archetype: Samurai': "samurai"
            },
        'MONK': {
            'Monastic Tradition: Way of Shadow': "shadow",
            'Monastic Tradition: Way of the Drunken Master': "drunken_master",
            'Monastic Tradition: Way of the Four Elements': "four_elements",
            'Monastic Tradition: Way of the Kensei': "kensei",
            'Monastic Tradition: Way of the Long Death': "long_death",
            'Monastic Tradition: Way of the Open Hand': "open_hand",
            'Monastic Tradition: Way of the Sun Soul': "sun_soul"
            },
        'PALADIN': {
            'Oathbreaker': "oathbreaker",
            'Sacred Oath: Oath of Conquest': "conquest",
            'Sacred Oath: Oath of Devotion': "devotion",
            'Sacred Oath: Oath of Redemption': "redemption",
            'Sacred Oath: Oath of Vengeance': "vengeance",
            'Sacred Oath: Oath of the Ancients': "ancients",
            'Sacred Oath: Oath of the Crown': "crown"
            },
        'RANGER': {
            'Ranger Archetype: Beast Master': "beast_master",
            'Ranger Archetype: Gloom Stalker': "gloom_stalker",
            'Ranger Archetype: Horizon Walker': "horizon_walker",
            'Ranger Archetype: Hunter': "hunter",
            'Ranger Archetype: Monster Slayer': "monster_slayer"
            },
        'ROGUE': {
            'Roguish Archetype: Arcane Trickster': "arcane_trickster",
            'Roguish Archetype: Assassin': "assassin",
            'Roguish Archetype: Inquisitive': "inquisitive",
            'Roguish Archetype: Mastermind': "mastermind",
            'Roguish Archetype: Scout': "scout",
            'Roguish Archetype: Swashbuckler': "swashbuckler",
            'Roguish Archetype: Thief': "thief"
            },
        'SORCERER': {
            'Sorcerous Origin: Divine Soul': "divine_soul",
            'Sorcerous Origin: Draconic Bloodline': "draconic_bloodline",
            'Sorcerous Origin: Shadow Magic': "shadow_magic",
            'Sorcerous Origin: Storm': "storm",
            'Sorcerous Origin: Wild Magic': "wild_magic"
            },
        'WARLOCK': {
            'Otherwordly Patron: The Celestial': "celestial",
            'Otherwordly Patron: The Hexblade': "hexblade",
            'Otherworldly Patron: The Archfey': "archfey",
            'Otherworldly Patron: The Fiend': "fiend",
            'Otherworldly Patron: The Great Old One': "great_old",
            'Otherworldly Patron: The Undying': "undying"
            },
        'WIZARD': {
            'Arcane Tradition: Bladesinger': "bladesinger",
            'Arcane Tradition: School of Abjuration': "abjuration",
            'Arcane Tradition: School of Conjuration': "conjuration",
            'Arcane Tradition: School of Divination': "divination",
            'Arcane Tradition: School of Enchantment': "enchantment",
            'Arcane Tradition: School of Evocation': "evocation",
            'Arcane Tradition: School of Illusion': "illusion",
            'Arcane Tradition: School of Necromancy': "necromancy",
            'Arcane Tradition: School of Transmutation': "transmutation",
            'Arcane Tradition: War Magic': "war_magic"
            }
        }
