col_names = ['prof_bonus', 'asi', 'inspiration', 'song_of_rest','spells_known', 'slots',]
data = { 1: { 'asi': '0',
       'inspiration': 'd6',
       'prof_bonus': '2',
       'slots': ['2', '2', '-', '-', '-', '-', '-', '-', '-', '-'],
       'song_of_rest': 'd6',
       'spells_known': '4'},
  2: { 'asi': '0',
       'inspiration': 'd6',
       'prof_bonus': '2',
       'slots': ['2', '3', '-', '-', '-', '-', '-', '-', '-', '-'],
       'song_of_rest': 'd6',
       'spells_known': '5'},
  3: { 'asi': '0',
       'inspiration': 'd6',
       'prof_bonus': '2',
       'slots': ['2', '4', '2', '-', '-', '-', '-', '-', '-', '-'],
       'song_of_rest': 'd6',
       'spells_known': '6'},
  4: { 'asi': '1',
       'inspiration': 'd6',
       'prof_bonus': '2',
       'slots': ['3', '4', '3', '-', '-', '-', '-', '-', '-', '-'],
       'song_of_rest': 'd6',
       'spells_known': '7'},
  5: { 'asi': '1',
       'inspiration': 'd8',
       'prof_bonus': '3',
       'slots': ['3', '4', '3', '2', '-', '-', '-', '-', '-', '-'],
       'song_of_rest': 'd6',
       'spells_known': '8'},
  6: { 'asi': '1',
       'inspiration': 'd8',
       'prof_bonus': '3',
       'slots': ['3', '4', '3', '3', '-', '-', '-', '-', '-', '-'],
       'song_of_rest': 'd6',
       'spells_known': '9'},
  7: { 'asi': '1',
       'inspiration': 'd8',
       'prof_bonus': '3',
       'slots': ['3', '4', '3', '3', '1', '-', '-', '-', '-', '-'],
       'song_of_rest': 'd6',
       'spells_known': '10'},
  8: { 'asi': '2',
       'inspiration': 'd8',
       'prof_bonus': '3',
       'slots': ['3', '4', '3', '3', '2', '-', '-', '-', '-', '-'],
       'song_of_rest': 'd6',
       'spells_known': '11'},
  9: { 'asi': '2',
       'inspiration': 'd8',
       'prof_bonus': '4',
       'slots': ['3', '4', '3', '3', '3', '1', '-', '-', '-', '-'],
       'song_of_rest': 'd8',
       'spells_known': '12'},
  10: { 'asi': '2',
        'inspiration': 'd10',
        'prof_bonus': '4',
        'slots': ['4', '4', '3', '3', '3', '2', '-', '-', '-', '-'],
        'song_of_rest': 'd8',
        'spells_known': '14'},
  11: { 'asi': '2',
        'inspiration': 'd10',
        'prof_bonus': '4',
        'slots': ['4', '4', '3', '3', '3', '2', '1', '-', '-', '-'],
        'song_of_rest': 'd8',
        'spells_known': '15'},
  12: { 'asi': '3',
        'inspiration': 'd10',
        'prof_bonus': '4',
        'slots': ['4', '4', '3', '3', '3', '2', '1', '-', '-', '-'],
        'song_of_rest': 'd8',
        'spells_known': '15'},
  13: { 'asi': '3',
        'inspiration': 'd10',
        'prof_bonus': '5',
        'slots': ['4', '4', '3', '3', '3', '2', '1', '1', '-', '-'],
        'song_of_rest': 'd10',
        'spells_known': '16'},
  14: { 'asi': '3',
        'inspiration': 'd10',
        'prof_bonus': '5',
        'slots': ['4', '4', '3', '3', '3', '2', '1', '1', '-', '-'],
        'song_of_rest': 'd10',
        'spells_known': '18'},
  15: { 'asi': '3',
        'inspiration': 'd12',
        'prof_bonus': '5',
        'slots': ['4', '4', '3', '3', '3', '2', '1', '1', '1', '-'],
        'song_of_rest': 'd10',
        'spells_known': '19'},
  16: { 'asi': '4',
        'inspiration': 'd12',
        'prof_bonus': '5',
        'slots': ['4', '4', '3', '3', '3', '2', '1', '1', '1', '-'],
        'song_of_rest': 'd10',
        'spells_known': '19'},
  17: { 'asi': '4',
        'inspiration': 'd12',
        'prof_bonus': '6',
        'slots': ['4', '4', '3', '3', '3', '2', '1', '1', '1', '1'],
        'song_of_rest': 'd12',
        'spells_known': '20'},
  18: { 'asi': '4',
        'inspiration': 'd12',
        'prof_bonus': '6',
        'slots': ['4', '4', '3', '3', '3', '3', '1', '1', '1', '1'],
        'song_of_rest': 'd12',
        'spells_known': '22'},
  19: { 'asi': '5',
        'inspiration': 'd12',
        'prof_bonus': '6',
        'slots': ['4', '4', '3', '3', '3', '3', '2', '1', '1', '1'],
        'song_of_rest': 'd12',
        'spells_known': '22'},
  20: { 'asi': '5',
        'inspiration': 'd12',
        'prof_bonus': '6',
        'slots': ['4', '4', '3', '3', '3', '3', '2', '2', '1', '1'],
        'song_of_rest': 'd12',
        'spells_known': '22'}}
